image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - init: echo 'set up Python 3'
    command: pyenv local 3.7.6
  - init: echo 'install updated pip'
    command: pip install --upgrade pip
  - init: echo 'more pips'
    command: pip install networkx dwave_networkx matplotlib pycodestyle
  - init: echo 'dwave'
    command: pip install dwave-ocean-sdk
